name: foodking
version: 1.0.10+15
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  animated_bottom_navigation_bar: ^1.2.0
  flutter_screenutil: ^5.7.0
  image_picker: ^1.1.2
  get_storage: ^2.1.1
  flutter_svg: ^2.0.5
  lottie: ^2.3.2
  timeline_tile: ^2.0.0
  contained_tab_bar_view: ^0.8.0
  toggle_switch: ^2.0.1
  another_stepper:
  expansion_tile_card: ^3.0.0
  expandable: ^5.0.1
  country_picker: ^2.0.20
  dropdown_button2: ^2.3.9
  flutter_chat_ui: ^1.6.6
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  google_maps_flutter: ^2.2.5
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  flutter_google_places: ^0.3.0
  flutter_typeahead: ^5.2.0
  custom_map_markers: ^0.0.2+1
  connectivity: ^3.0.6
  url_launcher: ^6.1.10
  webview_flutter: ^4.2.0
  firebase_messaging: ^15.1.2
  firebase_core: ^3.5.0
  flutter_local_notifications: ^17.2.2
  flutter_launcher_icons: ^0.14.1
  shared_preferences: ^2.1.0
  rflutter_alert: ^2.0.4
  im_stepper: ^1.0.1+1
  fluttertoast: ^8.2.1
  pinput: ^5.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_inappwebview: ^6.1.0+1
  path_provider: ^2.0.14
  map_launcher: ^3.5.0
  easy_stepper: ^0.8.3
  flutter_html:
  google_maps_flutter_ios: ^2.13.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#FFFFFF" # Solid color or background image
  adaptive_icon_foreground: "assets/images/app_logo.png" # Same as image_path


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animation/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-Black.ttf
          weight: 900
